module.exports = {
  port: process.env.PORT || 8000,
  host: process.env.HOST || 'localhost',
  googleClientID: process.env.GOOGLE_CLIENT_ID,
  googleClientSecretKey: process.env.GOOGLE_CLIENT_SECRET,
  facebookClientID: process.env.FACEBOOK_CLIENT_ID,
  facebookClientSecretKey: process.env.FACEBOOK_CLIENT_SECRET,
  instagramClientID: process.env.INSTAGRAM_CLIENT_ID,
  instagramClientSecretKey: process.env.INSTAGRAM_CLIENT_SECRET,
  linkedInClientID: process.env.LINKEDIN_CLIENT_ID,
  linkedInClientSecretKey: process.env.LINKEDIN_CLIENT_SECRET,
  gitHubClientID: process.env.GITHUB_CLIENT_ID,
  gitHubClientSecretKey: process.env.GITHUB_CLIENT_SECRET,
  spotifyClientID: process.env.SPOTIFY_CLIENT_ID,
  spotifyClientSecretKey: process.env.SPOTIFY_CLIENT_SECRET,
  mongodb_URI: process.env.MONGODB_URI,
  cookieKey: process.env.COOKIE_KEY,
};
